---
# tasks file for django_web

    - name: git repo
      git:
        repo: 'https://github.com/komarserjio/notejam.git'     
        dest: /opt/django
        force: yes
      become: yes

    - name: pip install virtualenv
      pip:
        name: virtualenv
      become: yes

    - name: create virtual environment django_env
      shell:
        cmd: virtualenv /opt/django_env
      become: yes
    
    - name: activate django_env virtual environment
      shell: source /opt/django_env/bin/activate
      args:
        executable: /bin/bash

    - name: pip install requirements
      pip:
        requirements: /opt/django/django/requirements.txt
        virtualenv: /opt/django_env
      become: yes
    
    - name: pip install mysql-python
      pip:
        name: mysql-python
        virtualenv: /opt/django_env
      become: yes

    - name: assign ENGINE
      become: yes      
      lineinfile: 
        path:  /opt/django/django/notejam/notejam/settings.py
        regexp: 'ENGINE'
        line: "'ENGINE': 'django.db.backends.mysql',"  

    - name: assign NAME
      become: yes
      lineinfile:
        path:  /opt/django/django/notejam/notejam/settings.py
        regexp: 'NAME'
        line: "'NAME': 'django_db',"

    - name: assign USER
      become: yes
      lineinfile:
        path:  /opt/django/django/notejam/notejam/settings.py
        regexp: 'USER'
        line: "'USER': 'db_user',"

    - name: assign PASSWORD
      become: yes
      lineinfile:
        path:  /opt/django/django/notejam/notejam/settings.py
        regexp: 'PASSWORD'
        line: "'PASSWORD': 'Passw0rd',"

    - name: assign HOST
      become: yes
      lineinfile:
        path: /opt/django/django/notejam/notejam/settings.py
        regexp: 'HOST'
        line: "'HOST': 'localhost',"

    - name: assign PORT
      become: yes
      lineinfile:
        path: /opt/django/django/notejam/notejam/settings.py
        regexp: 'PORT'
        line: "'PORT': '3306',"

    
    - name: execute script
      script: /opt/django/django/notejam/manage.py syncdb --noinput
      args:
        executable: /opt/django_env/bin/python2.7
      become: yes 


    - name: execute script
      script: /opt/django/django/notejam/manage.py migrate
      args:
        executable: /opt/django_env/bin/python2.7
      become: yes

    - name: Create file django_web.service file
      become: yes
      copy:
        dest: "/etc/systemd/system/django_web.service"
        content: |
          [Service]    
          ExecStart=/opt/django_env/bin/python2.7 /opt/django/django/notejam/manage.py runserver
          

    - name: Start running the server
      become: yes
      systemd:
        name: django_web.service
        state: started
